title: "Portfolio IT – Radosław Szydziak"
email: radekszydziak@gmail.com
theme: jekyll-theme-minimal
description: >-
  Projekty domowe z zakresu IT: IoT, AI, Cybersecurity, Automatyzacje, Cloud, Administracja

social_links:
  github: https://github.com/radoo96
  linkedin: https://www.linkedin.com/in/rados%C5%82aw-szydziak/
  blog: https://twoj-blog.pl
