title: "Portfolio – Radosław Szydziak"
email: radekszydziak@gmail.com
theme: jekyll-theme-minimal
description: >-
  Projekty domowe z zakresu: IoT, AI, Cybersecurity, Automatyzacje, Cloud, Administracja
