title: "Portfolio IT – Radosław Szydziak"
email: radoo96@gmail.com
theme: jekyll-theme-cayman
description: >- 
  Projekty domowe z zakresu IT: Raspberry Pi, Home Assistant, backupy, automatyzacje.
markdown: kramdown
