title: "Portfolio IT – Radosław Szydziak"
email: radekszydziak@gmail.com
theme: jekyll-theme-cayman
description: >- 
  Projekty domowe z zakresu IT: IoT, AI, Cybersecurity, Automatyzacje, Cloud, Administracja
markdown: kramdown
